### PR TITLE
Testing update to 19.4

### PR DESCRIPTION
**Pull request by patricksnape**

### CODE REVIEW

**Comment by y0ast** [comment]
It fails on opening the JPEG, even though opening the PNG is fine and and it clearly builds libjpeg from dlib/external.

🤔

**Comment by patricksnape** [comment]
Yeah it's annoying - need to make sure it doesn't build jpeg

**Comment by vchatterji** [comment]
@patricksnape and @y0ast 

It would be amazing if you guys could add support for 19.4. 19.3 adds the trained model for facial recognition which is a big change since 19.0

http://dlib.net/release_notes.html

I saw this patch in a separate repo:
https://github.com/menpo/conda-dlib/blob/master/conda/cmake_static_boost.patch

**Comment by patricksnape** [comment]
It's not boost that's failing - it's JPEG - also that repo is mine

**Comment by vchatterji** [comment]
@patricksnape cool! I thought the patch was compiling libjpeg in statically. 

Anyways, I'll leave you to it. Look forward to the package release 😀

**Comment by vchatterji** [comment]
@patricksnape why don't you release Linux and OSX packages while you guys figure out the Windows stuff?

**Comment by patricksnape** [comment]
OK - in theory I got this working - just waiting for builds to pass

**Pull request merged**
